apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastapi-mvc-example.fullname" . }}
  labels:
    {{- include "fastapi-mvc-example.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "fastapi-mvc-example.selectorLabels" . | nindent 4 }}
