
name: ❄️ Nix CI ❄️

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # This job checks if an identical workflow is being triggered by different
  # event and skips it. For instance there is no need to run the same pipeline
  # twice for pull_request and push for identical commit sha.
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5.2.0
        with:
          skip_after_successful_duplicate: 'true'
          concurrent_skipping: same_content
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'
  nix-build:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Nix ❄️
        uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"
          nix_path: nixpkgs=channel:nixos-22.05
      # Remove bellow step if you do not want to use Cachix - Nix binary cache.
      # For OpenSource projects there is free 5GB of storage.
      # https://www.cachix.org
      - name: Setup Cachix ❄️
        uses: cachix/cachix-action@v10
        with:
          name: fastapi-mvc
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Install make
        run: nix-env -i gnumake -f '<nixpkgs>'
      - name: Build package
        run: make build
      - name: Build container image
        run: make image
  nix-ci:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 'python38', 'python39', 'python310' ]
    env:
      PYTHON_NIXPKG: ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-22.05
      # Remove bellow step if you do not want to use Cachix - Nix binary cache.
      # For OpenSource projects there is free 5GB of storage.
      # https://www.cachix.org
      - name: Setup Cachix Nix cache
        uses: cachix/cachix-action@v10
        with:
          name: fastapi-mvc
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Install make
        run: nix-env -i gnumake -f '<nixpkgs>'
      - name: Run metrics checks
        run: make metrics
      - name: Run unit-tests
        run: make unit-test
      - name: Run integration-tests
        run: make integration-test