name: Update flake
on:
  workflow_dispatch:
#  # runs weekly on Sunday at 00:00
#  schedule:
#    - cron: '0 0 * * 0'

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v2
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v17
        with:
          pr-title: "Update flake.lock"
          # https://github.com/DeterminateSystems/update-flake-lock#with-a-personal-authentication-token
          token: ${{ secrets.API_TOKEN_GITHUB }}
          pr-labels: |
            dependencies
          pr-body: |
            Automated changes by the [update-flake-lock](https://github.com/DeterminateSystems/update-flake-lock) GitHub Action.
            ```
            {{ env.GIT_COMMIT_MESSAGE }}
            ```